2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_setup.py:_flush():75] Loading settings from /home/katia/.config/wandb/settings
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_setup.py:_flush():75] Loading settings from /home/katia/rep/intrinsic/wandb/settings
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'start_method': 'thread', 'project': 'icm', 'entity': 'katiavas'}
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_init.py:_log_setup():405] Logging user logs to ./wandb/run-20220325_192946-17sckuyv/logs/debug.log
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_init.py:_log_setup():406] Logging internal logs to ./wandb/run-20220325_192946-17sckuyv/logs/debug-internal.log
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_init.py:init():439] calling init triggers
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-25 19:29:46,171 INFO    MainThread:16071 [wandb_init.py:init():492] starting backend
2022-03-25 19:29:46,176 INFO    MainThread:16071 [backend.py:ensure_launched():219] starting backend process...
2022-03-25 19:29:46,176 INFO    MainThread:16071 [backend.py:ensure_launched():224] started backend process with pid: 0
2022-03-25 19:29:46,176 INFO    BackendThr:16071 [internal.py:wandb_internal():92] W&B internal server running at pid: 16071, started at: 2022-03-25 19:29:46.176394
2022-03-25 19:29:46,177 INFO    MainThread:16071 [wandb_init.py:init():501] backend started and connected
2022-03-25 19:29:46,182 INFO    MainThread:16071 [wandb_init.py:init():565] updated telemetry
2022-03-25 19:29:46,183 INFO    WriterThread:16071 [datastore.py:open_for_write():77] open: ./wandb/run-20220325_192946-17sckuyv/run-17sckuyv.wandb
2022-03-25 19:29:46,193 INFO    MainThread:16071 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-25 19:29:46,419 INFO    MainThread:16071 [wandb_run.py:_on_init():1759] communicating current version
2022-03-25 19:29:46,430 INFO    SenderThread:16071 [dir_watcher.py:__init__():169] watching files in: ./wandb/run-20220325_192946-17sckuyv/files
2022-03-25 19:29:46,431 INFO    SenderThread:16071 [sender.py:_start_run_threads():812] run started: 17sckuyv with start time 1648236586
2022-03-25 19:29:46,431 INFO    SenderThread:16071 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-03-25 19:29:46,531 INFO    MainThread:16071 [wandb_run.py:_on_init():1763] got version response 
2022-03-25 19:29:46,531 INFO    MainThread:16071 [wandb_init.py:init():625] starting run threads in backend
2022-03-25 19:29:47,434 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-17sckuyv/files/requirements.txt
2022-03-25 19:29:47,436 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-17sckuyv/files/conda-environment.yaml
2022-03-25 19:29:47,436 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-17sckuyv/files/wandb-summary.json
2022-03-25 19:29:51,595 INFO    MainThread:16071 [wandb_run.py:_console_start():1733] atexit reg
2022-03-25 19:29:51,596 INFO    MainThread:16071 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-25 19:29:51,597 INFO    MainThread:16071 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-25 19:29:51,679 INFO    MainThread:16071 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-25 19:29:51,680 INFO    MainThread:16071 [wandb_init.py:init():664] run started, returning control to user process
2022-03-25 19:29:53,547 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-17sckuyv/files/output.log
2022-03-25 19:30:09,727 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_modified():230] file/dir modified: ./wandb/run-20220325_192946-17sckuyv/files/conda-environment.yaml
2022-03-25 19:30:10,739 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-17sckuyv/files/wandb-metadata.json
2022-03-25 19:30:11,032 INFO    SenderThread:16071 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-03-25 19:30:11,817 INFO    Thread-20 :16071 [upload_job.py:push():137] Uploaded file /tmp/tmpexj3uywbwandb/2in5deul-wandb-metadata.json
2022-03-25 19:30:17,756 INFO    Thread-10 :16071 [dir_watcher.py:_on_file_modified():230] file/dir modified: ./wandb/run-20220325_192946-17sckuyv/files/config.yaml
2022-03-25 19:33:40,824 WARNING MsgRouterThr:16071 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-25 19:33:40,913 INFO    MainThread:16071 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-03-25 19:33:40,916 INFO    MainThread:16071 [wandb_run.py:_restore():1674] restore
2022-03-25 19:33:41,036 INFO    SenderThread:16071 [sender.py:finish():1078] shutting down sender
2022-03-25 19:33:41,036 INFO    SenderThread:16071 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-25 19:33:41,319 INFO    WriterThread:16071 [datastore.py:close():281] close: ./wandb/run-20220325_192946-17sckuyv/run-17sckuyv.wandb
2022-03-25 19:33:41,586 INFO    SenderThread:16071 [dir_watcher.py:finish():313] scan: ./wandb/run-20220325_192946-17sckuyv/files
2022-03-25 19:33:41,586 INFO    SenderThread:16071 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-17sckuyv/files/config.yaml config.yaml
2022-03-25 19:33:41,591 INFO    SenderThread:16071 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-17sckuyv/files/output.log output.log
2022-03-25 19:33:41,591 INFO    SenderThread:16071 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-17sckuyv/files/wandb-summary.json wandb-summary.json
2022-03-25 19:33:41,591 INFO    SenderThread:16071 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-17sckuyv/files/conda-environment.yaml conda-environment.yaml
2022-03-25 19:33:41,591 INFO    SenderThread:16071 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-17sckuyv/files/wandb-metadata.json wandb-metadata.json
2022-03-25 19:33:41,591 INFO    SenderThread:16071 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-17sckuyv/files/requirements.txt requirements.txt
2022-03-25 19:33:41,591 INFO    SenderThread:16071 [file_pusher.py:finish():145] shutting down file pusher
2022-03-25 19:33:41,595 INFO    SenderThread:16071 [file_pusher.py:join():150] waiting for file pusher
2022-03-25 19:33:42,169 INFO    Thread-23 :16071 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-17sckuyv/files/conda-environment.yaml
2022-03-25 19:33:42,180 INFO    Thread-21 :16071 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-17sckuyv/files/config.yaml
2022-03-25 19:33:42,185 INFO    Thread-24 :16071 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-17sckuyv/files/requirements.txt
2022-03-25 19:33:42,216 INFO    Thread-22 :16071 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-17sckuyv/files/wandb-summary.json
2022-03-25 19:33:42,760 ERROR   BackendThr:16071 [internal.py:wandb_internal():167] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 54, in run
    self._run()
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    record = self._input_record_q.get(timeout=1)
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/queues.py", line 111, in get
    res = self._recv_bytes()
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
