2022-03-25 19:29:46,286 INFO    MainThread:16072 [wandb_setup.py:_flush():75] Loading settings from /home/katia/.config/wandb/settings
2022-03-25 19:29:46,286 INFO    MainThread:16072 [wandb_setup.py:_flush():75] Loading settings from /home/katia/rep/intrinsic/wandb/settings
2022-03-25 19:29:46,286 INFO    MainThread:16072 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'start_method': 'thread', 'project': 'icm', 'entity': 'katiavas'}
2022-03-25 19:29:46,287 INFO    MainThread:16072 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-25 19:29:46,287 INFO    MainThread:16072 [wandb_init.py:_log_setup():405] Logging user logs to ./wandb/run-20220325_192946-1ss0crrs/logs/debug.log
2022-03-25 19:29:46,287 INFO    MainThread:16072 [wandb_init.py:_log_setup():406] Logging internal logs to ./wandb/run-20220325_192946-1ss0crrs/logs/debug-internal.log
2022-03-25 19:29:46,287 INFO    MainThread:16072 [wandb_init.py:init():439] calling init triggers
2022-03-25 19:29:46,287 INFO    MainThread:16072 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-25 19:29:46,287 INFO    MainThread:16072 [wandb_init.py:init():492] starting backend
2022-03-25 19:29:46,292 INFO    MainThread:16072 [backend.py:ensure_launched():219] starting backend process...
2022-03-25 19:29:46,292 INFO    MainThread:16072 [backend.py:ensure_launched():224] started backend process with pid: 0
2022-03-25 19:29:46,292 INFO    BackendThr:16072 [internal.py:wandb_internal():92] W&B internal server running at pid: 16072, started at: 2022-03-25 19:29:46.292271
2022-03-25 19:29:46,293 INFO    MainThread:16072 [wandb_init.py:init():501] backend started and connected
2022-03-25 19:29:46,298 INFO    MainThread:16072 [wandb_init.py:init():565] updated telemetry
2022-03-25 19:29:46,299 INFO    WriterThread:16072 [datastore.py:open_for_write():77] open: ./wandb/run-20220325_192946-1ss0crrs/run-1ss0crrs.wandb
2022-03-25 19:29:46,309 INFO    MainThread:16072 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-25 19:29:46,585 INFO    MainThread:16072 [wandb_run.py:_on_init():1759] communicating current version
2022-03-25 19:29:46,602 INFO    SenderThread:16072 [dir_watcher.py:__init__():169] watching files in: ./wandb/run-20220325_192946-1ss0crrs/files
2022-03-25 19:29:46,602 INFO    SenderThread:16072 [sender.py:_start_run_threads():812] run started: 1ss0crrs with start time 1648236586
2022-03-25 19:29:46,603 INFO    SenderThread:16072 [sender.py:_save_file():947] saving file wandb-summary.json with policy end
2022-03-25 19:29:46,783 INFO    MainThread:16072 [wandb_run.py:_on_init():1763] got version response 
2022-03-25 19:29:46,783 INFO    MainThread:16072 [wandb_init.py:init():625] starting run threads in backend
2022-03-25 19:29:47,607 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-1ss0crrs/files/conda-environment.yaml
2022-03-25 19:29:47,608 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-1ss0crrs/files/requirements.txt
2022-03-25 19:29:47,608 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-1ss0crrs/files/wandb-summary.json
2022-03-25 19:29:51,873 INFO    MainThread:16072 [wandb_run.py:_console_start():1733] atexit reg
2022-03-25 19:29:51,874 INFO    MainThread:16072 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-25 19:29:51,874 INFO    MainThread:16072 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-25 19:29:51,930 INFO    MainThread:16072 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-25 19:29:51,931 INFO    MainThread:16072 [wandb_init.py:init():664] run started, returning control to user process
2022-03-25 19:29:54,429 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-1ss0crrs/files/output.log
2022-03-25 19:30:12,496 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_modified():230] file/dir modified: ./wandb/run-20220325_192946-1ss0crrs/files/conda-environment.yaml
2022-03-25 19:30:12,497 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_created():217] file/dir created: ./wandb/run-20220325_192946-1ss0crrs/files/wandb-metadata.json
2022-03-25 19:30:12,909 INFO    SenderThread:16072 [sender.py:_save_file():947] saving file wandb-metadata.json with policy now
2022-03-25 19:30:13,836 INFO    Thread-20 :16072 [upload_job.py:push():137] Uploaded file /tmp/tmpcjetdgbywandb/2g4sauyk-wandb-metadata.json
2022-03-25 19:30:17,566 INFO    Thread-10 :16072 [dir_watcher.py:_on_file_modified():230] file/dir modified: ./wandb/run-20220325_192946-1ss0crrs/files/config.yaml
2022-03-25 19:33:40,824 WARNING MsgRouterThr:16072 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-25 19:33:40,840 INFO    MainThread:16072 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-03-25 19:33:40,843 INFO    MainThread:16072 [wandb_run.py:_restore():1674] restore
2022-03-25 19:33:41,135 INFO    WriterThread:16072 [datastore.py:close():281] close: ./wandb/run-20220325_192946-1ss0crrs/run-1ss0crrs.wandb
2022-03-25 19:33:41,531 INFO    SenderThread:16072 [sender.py:finish():1078] shutting down sender
2022-03-25 19:33:41,532 INFO    SenderThread:16072 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-25 19:33:41,739 INFO    SenderThread:16072 [dir_watcher.py:_on_file_modified():230] file/dir modified: ./wandb/run-20220325_192946-1ss0crrs/files/output.log
2022-03-25 19:33:41,740 INFO    SenderThread:16072 [dir_watcher.py:finish():313] scan: ./wandb/run-20220325_192946-1ss0crrs/files
2022-03-25 19:33:41,741 INFO    SenderThread:16072 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-1ss0crrs/files/config.yaml config.yaml
2022-03-25 19:33:41,741 INFO    SenderThread:16072 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-1ss0crrs/files/output.log output.log
2022-03-25 19:33:41,748 INFO    SenderThread:16072 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-1ss0crrs/files/wandb-summary.json wandb-summary.json
2022-03-25 19:33:41,748 INFO    SenderThread:16072 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-1ss0crrs/files/conda-environment.yaml conda-environment.yaml
2022-03-25 19:33:41,754 INFO    SenderThread:16072 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-1ss0crrs/files/wandb-metadata.json wandb-metadata.json
2022-03-25 19:33:41,755 INFO    SenderThread:16072 [dir_watcher.py:finish():327] scan save: ./wandb/run-20220325_192946-1ss0crrs/files/requirements.txt requirements.txt
2022-03-25 19:33:41,777 INFO    SenderThread:16072 [file_pusher.py:finish():145] shutting down file pusher
2022-03-25 19:33:41,781 INFO    SenderThread:16072 [file_pusher.py:join():150] waiting for file pusher
2022-03-25 19:33:42,363 INFO    Thread-23 :16072 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-1ss0crrs/files/wandb-summary.json
2022-03-25 19:33:42,367 INFO    Thread-24 :16072 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-1ss0crrs/files/conda-environment.yaml
2022-03-25 19:33:42,369 INFO    Thread-25 :16072 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-1ss0crrs/files/requirements.txt
2022-03-25 19:33:42,378 INFO    Thread-21 :16072 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-1ss0crrs/files/config.yaml
2022-03-25 19:33:42,445 INFO    Thread-22 :16072 [upload_job.py:push():137] Uploaded file ./wandb/run-20220325_192946-1ss0crrs/files/output.log
2022-03-25 19:33:42,964 ERROR   BackendThr:16072 [internal.py:wandb_internal():167] Thread HandlerThread:
Traceback (most recent call last):
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 54, in run
    self._run()
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    record = self._input_record_q.get(timeout=1)
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/queues.py", line 111, in get
    res = self._recv_bytes()
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/katia/anaconda3/envs/phil-env/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
